export const GET_POSTS_REQUESTED = 'GET_POSTS_REQUESTED';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAILED = 'GET_POSTS_FAILED';

export const SEARCH_TITLE_REQUESTED = 'SEARCH_TITLE_REQUESTED';
export const SEARCH_TITLE_SUCCESS = 'SEARCH_TITLE_SUCCESS';
export const SEARCH_TITLE_FAILED = 'SEARCH_TITLE_FAILED';
