export const GET_POSTS_REQUESTED = 'GET_POSTS_REQUESTED';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAILED = 'GET_POSTS_FAILED';

// export const SEARCH_POSTS_REQUESTED = 'SEARCH_POSTS_REQUESTED';
// export const SEARCH_POSTS_SUCCESS = 'SEARCH_POSTS_SUCCESS';
// export const SEARCH_POSTS_FAILED = 'SEARCH_POSTS_FAILED';
